CREATE TABLE bag (
  id INT PRIMARY KEY AUTO_INCREMENT,
  description VARCHAR(255) NOT NULL,
  detail VARCHAR(255),
  color VARCHAR(45),
  model VARCHAR(45),
  brand VARCHAR(45),
  image VARCHAR(255) NOT NULL,
  price DECIMAL(5,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
